export type RecoveryActionType = 'Retry Payment' | 'Retry Alternate Method' | 'Request Customer Action' | 'Delay Retry' | 'Manual Review' | 'Stop Recovery';
export type RecoveryActionStatus = 'Pending' | 'Scheduled' | 'Running' | 'Completed' | 'Failed' | 'Cancelled';
export type RecoveryOutcomeType = 'Recovered' | 'Failed' | 'Pending';

export interface MockRecoveryAttempt {
  id: string;
  attemptNumber: number;
  status: 'Started' | 'Failed' | 'Scheduled' | 'Completed';
  externalReference?: string;
  errorCode?: string;
  errorMessage?: string;
  startedAt?: string;
  completedAt?: string;
}

export interface MockRecoveryOutcome {
  outcomeType: RecoveryOutcomeType;
  recoveredAmount: number;
  status: 'Completed' | 'Pending' | 'Failed';
  externalReference?: string;
  failureReason?: string;
  occurredAt?: string;
}

export interface MockRecoveryTimelineEvent {
  id: string;
  date: string;
  title: string;
  description: string;
  type: 'system' | 'decision' | 'attempt' | 'outcome';
  status: 'info' | 'warning' | 'success' | 'error';
}

export interface MockRecoveryAction {
  id: string;
  riskCaseId: string;
  paymentId: string;
  customerId: string;
  customerName: string;
  customerEmail: string;
  amount: number;
  currency: string;
  actionType: RecoveryActionType;
  status: RecoveryActionStatus;
  scheduledAt?: string;
  executedAt?: string;
  createdAt: string;
  notes?: string;

  aiDecision: {
    recommendedAction: string;
    confidence: number;
    reasoning: string;
  };

  risk: {
    level: 'Critical' | 'High' | 'Medium' | 'Low';
    score: number;
    recoveryProbability: number;
  };

  attempts: MockRecoveryAttempt[];
  outcome: MockRecoveryOutcome;
  timeline: MockRecoveryTimelineEvent[];
}

export const initialMockRecoveryActions: MockRecoveryAction[] = [
  {
    id: "RA-10482",
    riskCaseId: "RC-10482",
    paymentId: "pay_Qx82491",
    customerId: "cus_101",
    customerName: "John Mathews",
    customerEmail: "john@example.com",
    amount: 42000,
    currency: "INR",
    actionType: "Retry Payment",
    status: "Scheduled",
    scheduledAt: "Today, 10:45 AM",
    createdAt: "2h ago",
    aiDecision: {
      recommendedAction: "Retry payment with Smart Routing",
      confidence: 94,
      reasoning: "Payment has a high recovery probability after transient network failures."
    },
    risk: {
      level: "Critical",
      score: 0.91,
      recoveryProbability: 86
    },
    attempts: [
      { id: "att_1", attemptNumber: 1, status: "Started", startedAt: "Today, 10:12 AM" },
      { id: "att_2", attemptNumber: 2, status: "Failed", errorCode: "BANK_UNAVAILABLE", errorMessage: "Issuer network timeout", startedAt: "Today, 10:24 AM", completedAt: "Today, 10:25 AM" },
      { id: "att_3", attemptNumber: 3, status: "Scheduled", startedAt: "Today, 10:45 AM" }
    ],
    outcome: {
      outcomeType: "Pending",
      recoveredAmount: 0,
      status: "Pending"
    },
    timeline: [
      { id: "t1", date: new Date(Date.now() - 7200000).toISOString(), title: "Action Planned", description: "Retry Payment action generated by AI", type: "decision", status: "info" },
      { id: "t2", date: new Date(Date.now() - 7100000).toISOString(), title: "Attempt #1", description: "Smart Routing Retry", type: "attempt", status: "info" },
      { id: "t3", date: new Date(Date.now() - 6500000).toISOString(), title: "Attempt #2", description: "Failed: Bank Unavailable", type: "attempt", status: "error" },
      { id: "t4", date: new Date(Date.now() - 3600000).toISOString(), title: "Scheduled", description: "Attempt #3 scheduled for 10:45 AM", type: "system", status: "info" }
    ]
  },
  {
    id: "RA-10483",
    riskCaseId: "RC-10484",
    paymentId: "pay_Qx82497",
    customerId: "cus_108",
    customerName: "Initech",
    customerEmail: "accounts@initech.com",
    amount: 18000,
    currency: "INR",
    actionType: "Request Customer Action",
    status: "Completed",
    executedAt: "1d ago",
    createdAt: "3d ago",
    aiDecision: {
      recommendedAction: "Send SMS payment link",
      confidence: 81,
      reasoning: "Hard decline on wallet, but customer responsive to SMS in past."
    },
    risk: {
      level: "Medium",
      score: 0.45,
      recoveryProbability: 72
    },
    attempts: [
      { id: "att_1", attemptNumber: 1, status: "Completed", externalReference: "sms_77812", startedAt: "3d ago", completedAt: "1d ago" }
    ],
    outcome: {
      outcomeType: "Recovered",
      recoveredAmount: 18000,
      status: "Completed",
      externalReference: "rec_10483",
      occurredAt: "1d ago"
    },
    timeline: [
      { id: "t1", date: new Date(Date.now() - 259200000).toISOString(), title: "Action Planned", description: "Customer Action Request generated", type: "decision", status: "info" },
      { id: "t2", date: new Date(Date.now() - 259000000).toISOString(), title: "SMS Sent", description: "Payment link delivered to customer", type: "attempt", status: "info" },
      { id: "t3", date: new Date(Date.now() - 86400000).toISOString(), title: "Recovery Successful", description: "Payment captured successfully", type: "outcome", status: "success" }
    ]
  },
  {
    id: "RA-10484",
    riskCaseId: "RC-10485",
    paymentId: "pay_Qx82499",
    customerId: "cus_112",
    customerName: "Cyberdyne Systems",
    customerEmail: "billing@cyberdyne.com",
    amount: 42000,
    currency: "INR",
    actionType: "Retry Alternate Method",
    status: "Pending",
    createdAt: "4d ago",
    aiDecision: {
      recommendedAction: "Request alternate payment method",
      confidence: 85,
      reasoning: "Card limit reached. Customer needs to switch method."
    },
    risk: {
      level: "High",
      score: 0.75,
      recoveryProbability: 60
    },
    attempts: [],
    outcome: {
      outcomeType: "Pending",
      recoveredAmount: 0,
      status: "Pending"
    },
    timeline: [
      { id: "t1", date: new Date(Date.now() - 345600000).toISOString(), title: "Action Planned", description: "Alternate Method action generated", type: "decision", status: "info" }
    ]
  },
  {
    id: "RA-10485",
    riskCaseId: "RC-10488",
    paymentId: "pay_Qx82510",
    customerId: "cus_120",
    customerName: "Stark Industries",
    customerEmail: "tony@stark.com",
    amount: 125000,
    currency: "INR",
    actionType: "Manual Review",
    status: "Failed",
    executedAt: "2d ago",
    createdAt: "5d ago",
    aiDecision: {
      recommendedAction: "Route to risk team",
      confidence: 90,
      reasoning: "High value transaction with compliance flags."
    },
    risk: {
      level: "Critical",
      score: 0.95,
      recoveryProbability: 10
    },
    attempts: [
      { id: "att_1", attemptNumber: 1, status: "Failed", errorMessage: "Compliance review rejected", startedAt: "3d ago", completedAt: "2d ago" }
    ],
    outcome: {
      outcomeType: "Failed",
      recoveredAmount: 0,
      status: "Failed",
      failureReason: "Compliance block. Risk team rejected.",
      occurredAt: "2d ago"
    },
    timeline: [
      { id: "t1", date: new Date(Date.now() - 432000000).toISOString(), title: "Action Planned", description: "Routed to Manual Review queue", type: "decision", status: "info" },
      { id: "t2", date: new Date(Date.now() - 259200000).toISOString(), title: "Review Started", description: "Risk team assigned", type: "attempt", status: "warning" },
      { id: "t3", date: new Date(Date.now() - 172800000).toISOString(), title: "Recovery Failed", description: "Compliance rejected retry.", type: "outcome", status: "error" }
    ]
  },
  {
    id: "RA-10486",
    riskCaseId: "RC-10490",
    paymentId: "pay_Qx82515",
    customerId: "cus_125",
    customerName: "Wayne Enterprises",
    customerEmail: "bruce@wayne.com",
    amount: 55000,
    currency: "INR",
    actionType: "Delay Retry",
    status: "Running",
    createdAt: "1h ago",
    scheduledAt: "Tomorrow, 09:00 AM",
    aiDecision: {
      recommendedAction: "Delay retry 24h",
      confidence: 88,
      reasoning: "Recurring billing cycle aligns better tomorrow morning."
    },
    risk: {
      level: "Medium",
      score: 0.55,
      recoveryProbability: 82
    },
    attempts: [
       { id: "att_1", attemptNumber: 1, status: "Started", startedAt: "1h ago" }
    ],
    outcome: {
      outcomeType: "Pending",
      recoveredAmount: 0,
      status: "Pending"
    },
    timeline: [
      { id: "t1", date: new Date(Date.now() - 3600000).toISOString(), title: "Action Planned", description: "Delay Retry action generated", type: "decision", status: "info" },
      { id: "t2", date: new Date(Date.now() - 1800000).toISOString(), title: "Timer Started", description: "Waiting for scheduled window", type: "system", status: "info" }
    ]
  }
];

export const recoveryKpiMetrics = {
  recoverableRevenue: "₹5.16L",
  recoveryActions: 284,
  pendingActions: 76,
  attempts: 612,
  recoveredRevenue: "₹2.14L",
  recoveryRate: "41.5%"
};

export const recoveryPipelineStats = [
  { stage: "Eligible", count: 184, amount: "₹5.16L" },
  { stage: "Action Planned", count: 121, amount: "₹3.72L" },
  { stage: "Scheduled", count: 94, amount: "₹2.81L" },
  { stage: "Attempted", count: 72, amount: "₹2.34L" },
  { stage: "Recovered", count: 51, amount: "₹2.14L" }
];

export const strategyPerformance = [
  { name: "Retry Payment", attempts: 182, successful: 74, rate: 40.7, recovered: "₹92K" },
  { name: "Alternate Payment Method", attempts: 96, successful: 48, rate: 50.0, recovered: "₹68K" },
  { name: "Customer Action Request", attempts: 72, successful: 21, rate: 29.2, recovered: "₹31K" },
  { name: "Delay Retry", attempts: 154, successful: 88, rate: 57.1, recovered: "₹1.4L" }
];

export const topOpportunities = [
  { customer: "John Mathews", payment: "pay_Qx82491", amount: 42000, probability: 86, action: "Retry Payment", status: "Scheduled" },
  { customer: "Sarah Kumar", payment: "pay_Qx82495", amount: 31500, probability: 79, action: "Alternate Method", status: "Ready" },
  { customer: "Acme Corp", payment: "pay_Qx82522", amount: 150000, probability: 92, action: "Delay Retry", status: "Pending" }
];
